SPHINX_THEMES_HTML_THEME = 'classic'
SPHINX_THEMES_HTML_THEME_OPTIONS = {}
SPHINX_THEMES_EXTRA_STYLESHEETS = []
SPHINX_THEMES_EXTRA_SCRIPTS = []
SPHINX_THEMES_SHOW_SOURCE = True

SPHINX_THEMES_SEARCH_URL = '/search.html'

SPHINX_THEMES_TOC_CAPTION = ''
SPHINX_THEMES_COPYRIGHT = ''
SPHINX_THEMES_MASTER_DOC = ''
SPHINX_THEMES_DOCSTITLE = ''
SPHINX_THEMES_SHORTTITLE = ''
SPHINX_THEMES_PROJECT = ''
SPHINX_THEMES_LANGUAGE = ''
SPHINX_THEMES_RELEASE = ''
SPHINX_THEMES_LAST_UPDATED = ''
SPHINX_THEMES_LOGO = ''
SPHINX_THEMES_LOGO_URL = ''
SPHINX_THEMES_FAVICON = ''
SPHINX_THEMES_SPHINX_VERSION = ''
SPHINX_THEMES_SHOW_COPYRIGHT = False
SPHINX_THEMES_SHOW_SPHINX = False
SPHINX_THEMES_DISPLAY_TOC = True


def SPHINX_THEMES_VERSION(context):
    return context.settings.EXTRA_CONTEXT.get('GIT_VERSION', '')
